version: '3.9'
services:
  rondon_bot:
    build: .
    container_name: rondon_bot
    env_file:
     - .env
    links:
      - lavalink
    depends_on:
      - lavalink

  lavalink:
    image: fredboat/lavalink:master
    container_name: rondon_bot_lavalink
    restart: always
    volumes:
     - ./lavalink.yml:/opt/Lavalink/application.yml

volumes:
  rod_db:
    driver: local
