name: rondon_bot
description: A discord bot
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  nyxx: ^3.4.2
  nyxx_interactions: ^4.2.1
  nyxx_commands: ^4.2.0 
  nyxx_lavalink: ^3.0.1
  duration: ^3.0.11

